name: ci

on: [push, pull_request]

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: accumulo
          - image: dns
          - image: centos7-oj11
            platforms: linux/amd64,linux/arm64
          - image: centos7-oj11-openldap-referrals
            platforms: linux/amd64,linux/arm64
          - image: spark3.0-iceberg
          - image: spark3-delta
          - image: kerberos
            test: kerberos
          - image: gpdb-6
            test: gpdb-6
          - image: hdp2.6-hive-kerberized-2
          - image: hive3.1-hive
            imag: hive3.1-hive
          - image: hdp2.6-hive-kerberized
            test: hdp2.6-hive
          - image: hdp3.1-hive-kerberized
            test: hdp3.1-hive
          - image: cdh5.12-hive-kerberized
            test: cdh5.12-hive
          - image: cdh5.15-hive-kerberized
            test: cdh5.15-hive
          - image: cdh5.15-hive-kerberized-kms
          - image: phoenix5
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # checkout tags so version in Manifest is set properly
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build ${{ matrix.config.image }}
      run: make "testing/${{ matrix.config.image }}" PLATFORMS=${{ matrix.config.platforms }}
    - name: Test ${{ matrix.config.test }}
      if: ${{ matrix.config.test  != '' }}
      shell: 'script -q -e -c "bash {0}"'
      run: make test IMAGE_TO_TEST="${{ matrix.config.test }}"
